### PR TITLE
Add Feature-wise Linear Modulation layer (from pytorch/#9177)

### PR DESCRIPTION
**Pull request by SsnL**
Commits:

1.  Add FiLM https://github.com/pytorch/pytorch/pull/9177
2. Port `common.py` from pytorch core (with several unrelated methods/flags removed), and add test for FiLM

Test plan:
1. install via `python setup.py install`
2. `python test/test_nn.py -vf`

cc @ethanjperez

### CODE REVIEW

**Comment by ethanjperez** [comment]
Thanks for doing this!

Does view() in this implementation call contiguous()? I thought it may have been sometimes calling contiguous(), which may be worth avoiding depending on how expensive that is.

There's also a small typo in one of the (helpful) error messages you added:
"film expects input to be at 2-dimensional" -> "film expects input to be at least 2-dimensional"

**Comment by SsnL** [comment]
@ethanjperez Thanks for pointing out the typo. Fixed in new commit.

Re: `.view` since it only adds dimensions of size `1`, it will never call `.contiguous` (i.e., not copy). (We made a change a while ago so that as long as the strides are compatible, you can call `.view` on even non-contiguous tensors.) And since it is 1 op rather than multiples, it should be faster than keep calling `.unsqueeze`. :)

**Comment by ethanjperez** [comment]
No problem and great! That makes sense :)

**Comment by SsnL** [comment]
reopen to trigger travis

**Comment by SsnL** [comment]
@ethanjperez just an update. I will work on enabling CI on contrib next week, and then we can get this going.

**Comment by ethanjperez** [comment]
@SsnL Great sounds good - thanks so much!

**Pull request merged**
